### PR TITLE
Show schema when user presses show button

### PR DESCRIPTION
**Pull request by IonGyth**

### CODE REVIEW

**Comment by jk2K** [comment]
thanks, Can you give a screenshot and show the effect of this commit?

**Comment by IonGyth** [comment]
Firstly, thanks for responding. I'm not very familiar with GitHub so bare with me! Just to give you some information about why this was required.
Steps to replicate:
1. Click "Show" for either a Request or a Response
1a. The box should drop down with Headers, Attributes, Body, and Schema,
2. Click "Show" for the Schema
3. The Schema should not show

I found this was because when clicking this the "max-height" style attribute was set on "collapse-content" but since the "JsonSchemaContent" was hidden then it could not get the height of that div.

I'll be more than happy to provide screenshots if you request it but I'm not sure if they will add much!

**Comment by IonGyth** [comment]
Oh, I also made this change on the olio-theme branch then merged that into publish-patch-for-olio-theme. I don't really want to create two pull requests with basically the same thing but once you're happy with everything then maybe you could merge it into there.

I'll take your guidance on what you think is best for that.

**Comment by IonGyth** [comment]
Hey! What do you think?

**Pull request merged**
